DROP PROCEDURE IF EXISTS create_booking_with_payment(INTEGER, INTEGER, INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, TEXT, OUT INTEGER, OUT INTEGER);
DROP PROCEDURE IF EXISTS confirm_payment(INTEGER, TEXT);
DROP PROCEDURE IF EXISTS cancel_booking_with_refund(INTEGER);
